version: '3.4'

services:
  pc2:
    image: pc2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9000:9000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
